version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: hoagie-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: hoagie-hub

volumes:
  mongodb_data: